## Abigail Paterson Coding Discussion 3

In [1]:
#import libraries
import pandas as pd

In [36]:
#read in the chicago crime data
data = pd.read_csv("chicago_summer_2018_crime_data.csv")
#look at data structure
print(len(data))
data.head()

73373

,month,day,year,day_of_week,description,location_description,block,primary_type,district,ward,arrest,domestic,latitude,longitude
0,8,4,2018,Saturday,FROM BUILDING,APARTMENT,039XX W WASHINGTON BLVD,THEFT,11,28.0,False,False,NaN,NaN
1,7,26,2018,Thursday,POCKET-PICKING,RESTAURANT,005XX W MADISON ST,THEFT,1,42.0,False,False,NaN,NaN
2,6,24,2018,Sunday,BOGUS CHECK,GROCERY FOOD STORE,004XX E 34TH ST,DECEPTIVE PRACTICE,2,4.0,False,False,NaN,NaN
3,6,13,2018,Wednesday,SIMPLE,RESIDENCE,098XX S EXCHANGE AVE,ASSAULT,4,10.0,False,True,NaN,NaN
4,6,14,2018,Thursday,TO VEHICLE,STREET,001XX S WALLER AVE,CRIMINAL DAMAGE,15,29.0,False,False,NaN,NaN

In [63]:
#find total amount of each crime 
totals = pd.DataFrame(data.groupby(['primary_type']).size().reset_index(name = "total_count"))
totals

                         primary_type  total_count
0                               ARSON          112
1                             ASSAULT         5635
2                             BATTERY        14111
3                            BURGLARY         3390
4   CONCEALED CARRY LICENSE VIOLATION           44
5                 CRIM SEXUAL ASSAULT          430
6                     CRIMINAL DAMAGE         7931
7                   CRIMINAL TRESPASS         1779
8                  DECEPTIVE PRACTICE         4684
9                            GAMBLING          115
10                           HOMICIDE          172
11                  HUMAN TRAFFICKING            2
12   INTERFERENCE WITH PUBLIC OFFICER          374
13                       INTIMIDATION           54
14                         KIDNAPPING           47
15               LIQUOR LAW VIOLATION           83
16                MOTOR VEHICLE THEFT         2608
17                          NARCOTICS         3047
18                       NON-CRIMINAL            8
19   NON-CRIMINAL (SUBJECT SPECIFIED)            2
20                          OBSCENITY           21
21         OFFENSE INVOLVING CHILDREN          532
22                      OTHER OFFENSE         4478
23                       PROSTITUTION          185
24                   PUBLIC INDECENCY            5
25             PUBLIC PEACE VIOLATION          372
26                            ROBBERY         2680
27                        SEX OFFENSE          276
28                           STALKING           54
29                              THEFT        18541
30                  WEAPONS VIOLATION         1601

In [68]:
#group by both day and primary type and assign to new dataframe
grouped = pd.DataFrame(data.groupby(['primary_type', 'day']).size().reset_index(name = "daily_count"))
#check new dataframe
grouped

          primary_type  day  daily_count
0                ARSON    1            4
1                ARSON    2            3
2                ARSON    3            3
3                ARSON    4            2
4                ARSON    5            4
..                 ...  ...          ...
797  WEAPONS VIOLATION   27           46
798  WEAPONS VIOLATION   28           51
799  WEAPONS VIOLATION   29           66
800  WEAPONS VIOLATION   30           56
801  WEAPONS VIOLATION   31           39

[802 rows x 3 columns]

In [69]:
#merge two together for easier division
grouped = grouped.merge(totals, how="left", on="primary_type")
grouped

          primary_type  day  daily_count  total_count
0                ARSON    1            4          112
1                ARSON    2            3          112
2                ARSON    3            3          112
3                ARSON    4            2          112
4                ARSON    5            4          112
..                 ...  ...          ...          ...
797  WEAPONS VIOLATION   27           46         1601
798  WEAPONS VIOLATION   28           51         1601
799  WEAPONS VIOLATION   29           66         1601
800  WEAPONS VIOLATION   30           56         1601
801  WEAPONS VIOLATION   31           39         1601

[802 rows x 4 columns]

In [73]:
#create new column to hold portion of crime committed on any given day
grouped['proportion'] = round(grouped['daily_count']/grouped['total_count'], 2)
grouped

          primary_type  day  daily_count  total_count  proportion
0                ARSON    1            4          112        0.04
1                ARSON    2            3          112        0.03
2                ARSON    3            3          112        0.03
3                ARSON    4            2          112        0.02
4                ARSON    5            4          112        0.04
..                 ...  ...          ...          ...         ...
797  WEAPONS VIOLATION   27           46         1601        0.03
798  WEAPONS VIOLATION   28           51         1601        0.03
799  WEAPONS VIOLATION   29           66         1601        0.04
800  WEAPONS VIOLATION   30           56         1601        0.03
801  WEAPONS VIOLATION   31           39         1601        0.02

[802 rows x 5 columns]

In [77]:
#pivot table so each type only has one row
data_by_type = grouped.pivot_table(values='proportion', columns='day', index='primary_type', fill_value=0)
data_by_type

day,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
primary_type,,,,,,,,,,,,,,,,,,,,,
ARSON,0.04,0.03,0.03,0.02,0.04,0.05,0.04,0.04,0.02,0.02,...,0.04,0.01,0.05,0.01,0.02,0.01,0.03,0.05,0.03,0.03
ASSAULT,0.04,0.03,0.03,0.04,0.04,0.03,0.03,0.03,0.03,0.03,...,0.03,0.03,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.02
BATTERY,0.04,0.04,0.03,0.04,0.03,0.03,0.03,0.03,0.03,0.03,...,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.02
BURGLARY,0.04,0.03,0.03,0.03,0.03,0.04,0.03,0.03,0.03,0.03,...,0.04,0.03,0.04,0.03,0.03,0.04,0.03,0.03,0.03,0.02
CONCEALED CARRY LICENSE VIOLATION,0.05,0.02,0.05,0.05,0.02,0.05,0.05,0.00,0.02,0.05,...,0.02,0.00,0.05,0.07,0.07,0.02,0.02,0.00,0.02,0.05
CRIM SEXUAL ASSAULT,0.06,0.02,0.04,0.05,0.04,0.04,0.03,0.04,0.03,0.03,...,0.03,0.03,0.02,0.03,0.05,0.03,0.03,0.03,0.03,0.01
CRIMINAL DAMAGE,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,...,0.04,0.04,0.03,0.03,0.04,0.04,0.03,0.03,0.03,0.02
CRIMINAL TRESPASS,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.04,0.04,0.03,...,0.03,0.04,0.04,0.03,0.03,0.04,0.04,0.03,0.03,0.02
DECEPTIVE PRACTICE,0.04,0.04,0.03,0.03,0.03,0.04,0.03,0.03,0.03,0.03,...,0.03,0.03,0.03,0.03,0.03,0.04,0.03,0.03,0.03,0.03
GAMBLING,0.07,0.03,0.02,0.01,0.03,0.02,0.03,0.03,0.05,0.04,...,0.02,0.02,0.01,0.04,0.03,0.01,0.02,0.03,0.03,0.03
HOMICIDE,0.02,0.00,0.03,0.02,0.06,0.03,0.02,0.08,0.05,0.05,...,0.02,0.03,0.03,0.03,0.03,0.03,0.02,0.02,0.03,0.02
HUMAN TRAFFICKING,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.50,0.00,0.00,0.00,0.00
INTERFERENCE WITH PUBLIC OFFICER,0.03,0.02,0.05,0.03,0.02,0.04,0.04,0.05,0.04,0.05,...,0.04,0.03,0.02,0.03,0.04,0.03,0.04,0.03,0.03,0.01
INTIMIDATION,0.02,0.04,0.00,0.04,0.02,0.04,0.02,0.02,0.04,0.06,...,0.00,0.04,0.00,0.07,0.00,0.11,0.04,0.02,0.04,0.02
KIDNAPPING,0.02,0.04,0.02,0.04,0.09,0.02,0.00,0.02,0.00,0.02,...,0.00,0.09,0.02,0.06,0.04,0.09,0.02,0.00,0.04,0.00
LIQUOR LAW VIOLATION,0.02,0.05,0.05,0.02,0.02,0.01,0.04,0.01,0.07,0.04,...,0.00,0.01,0.00,0.06,0.00,0.05,0.06,0.02,0.01,0.00
MOTOR VEHICLE THEFT,0.03,0.03,0.04,0.03,0.02,0.04,0.03,0.03,0.03,0.03,...,0.03,0.03,0.04,0.03,0.03,0.03,0.03,0.03,0.04,0.02
NARCOTICS,0.04,0.03,0.04,0.03,0.03,0.04,0.03,0.03,0.03,0.03,...,0.04,0.03,0.03,0.04,0.03,0.03,0.03,0.03,0.03,0.03
NON-CRIMINAL,0.00,0.00,0.00,0.00,0.00,0.12,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.25,0.00,0.00,0.12,0.00,0.12
NON-CRIMINAL (SUBJECT SPECIFIED),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.50,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
OBSCENITY,0.14,0.00,0.05,0.10,0.00,0.05,0.00,0.00,0.00,0.00,...,0.05,0.00,0.05,0.05,0.10,0.10,0.05,0.05,0.05,0.05
OFFENSE INVOLVING CHILDREN,0.06,0.03,0.04,0.04,0.03,0.02,0.03,0.04,0.03,0.04,...,0.03,0.02,0.02,0.03,0.02,0.04,0.03,0.02,0.04,0.02
OTHER OFFENSE,0.04,0.03,0.03,0.03,0.03,0.04,0.04,0.03,0.03,0.03,...,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.02
PROSTITUTION,0.06,0.01,0.02,0.01,0.02,0.02,0.00,0.08,0.01,0.03,...,0.03,0.06,0.03,0.03,0.04,0.05,0.03,0.05,0.09,0.01
PUBLIC INDECENCY,0.00,0.00,0.00,0.20,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
PUBLIC PEACE VIOLATION,0.03,0.04,0.03,0.05,0.03,0.05,0.03,0.04,0.05,0.03,...,0.01,0.03,0.05,0.02,0.04,0.03,0.04,0.02,0.03,0.01
ROBBERY,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.04,0.04,...,0.04,0.03,0.03,0.03,0.04,0.04,0.03,0.04,0.04,0.02
SEX OFFENSE,0.03,0.04,0.01,0.04,0.03,0.03,0.04,0.03,0.03,0.04,...,0.04,0.03,0.03,0.04,0.01,0.01,0.05,0.03,0.03,0.02
STALKING,0.06,0.07,0.06,0.06,0.00,0.06,0.00,0.04,0.04,0.00,...,0.00,0.09,0.06,0.02,0.07,0.00,0.04,0.04,0.02,0.00
THEFT,0.03,0.04,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.04,...,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.02
WEAPONS VIOLATION,0.03,0.03,0.03,0.04,0.04,0.03,0.03,0.03,0.03,0.03,...,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.04,0.03,0.02