In [39]:
#importing pandas module
import pandas as pd 

#importing Chicago CSV and assinging it the name "dat"
dat=pd.read_csv("/Users/ellisobrien/Desktop/Georgetown Semester 1/Data Science/coding_discussions_ppol564_fall2021/03_coding_discussion/chicago_summer_2018_crime_data.csv")

          primary_type  day  crimecount
0                ARSON    1           4
1                ARSON    2           3
2                ARSON    3           3
3                ARSON    4           2
4                ARSON    5           4
..                 ...  ...         ...
797  WEAPONS VIOLATION   27          46
798  WEAPONS VIOLATION   28          51
799  WEAPONS VIOLATION   29          66
800  WEAPONS VIOLATION   30          56
801  WEAPONS VIOLATION   31          39

[802 rows x 3 columns]

In [64]:

#creating data frame and grouping by crime type and day
days = dat.groupby(['primary_type','day']).size().reset_index(name = 'crimecount_byday')

days[:5]

                        primary_type  crimecount_all
0                              ARSON             112
1                            ASSAULT            5635
2                            BATTERY           14111
3                           BURGLARY            3390
4  CONCEALED CARRY LICENSE VIOLATION              44

In [65]:
#creating data frame group just by type 
crime= dat.groupby(['primary_type']).size().reset_index(name = 'crimecount_all')

crime[:5]

                        primary_type  crimecount_all
0                              ARSON             112
1                            ASSAULT            5635
2                            BATTERY           14111
3                           BURGLARY            3390
4  CONCEALED CARRY LICENSE VIOLATION              44

In [66]:
#joining two tables with right join
crime_joined = crime.merge(days, on='primary_type', how='right')

#creating new column with crime rate by day 
crime_joined['crime_rate'] = round(crime_joined['crimecount_byday']/crime_joined['crimecount_all'], 2)

crime_joined [:5]

  primary_type  crimecount_all  day  crimecount_byday  crime_rate
0        ARSON             112    1                 4        0.04
1        ARSON             112    2                 3        0.03
2        ARSON             112    3                 3        0.03
3        ARSON             112    4                 2        0.02
4        ARSON             112    5                 4        0.04

In [67]:
#pivoting crime rate values so that days are columns 
crime_pivoted=crime_joined.pivot_table(values = 'crime_rate', index = 'primary_type', columns = 'day')


#adding 0's as NA's 
crime_pivoted.fillna(0.00)

day,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
primary_type,,,,,,,,,,,,,,,,,,,,,
ARSON,0.04,0.03,0.03,0.02,0.04,0.05,0.04,0.04,0.02,0.02,...,0.04,0.01,0.05,0.01,0.02,0.01,0.03,0.05,0.03,0.03
ASSAULT,0.04,0.03,0.03,0.04,0.04,0.03,0.03,0.03,0.03,0.03,...,0.03,0.03,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.02
BATTERY,0.04,0.04,0.03,0.04,0.03,0.03,0.03,0.03,0.03,0.03,...,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.02
BURGLARY,0.04,0.03,0.03,0.03,0.03,0.04,0.03,0.03,0.03,0.03,...,0.04,0.03,0.04,0.03,0.03,0.04,0.03,0.03,0.03,0.02
CONCEALED CARRY LICENSE VIOLATION,0.05,0.02,0.05,0.05,0.02,0.05,0.05,0.00,0.02,0.05,...,0.02,0.00,0.05,0.07,0.07,0.02,0.02,0.00,0.02,0.05
CRIM SEXUAL ASSAULT,0.06,0.02,0.04,0.05,0.04,0.04,0.03,0.04,0.03,0.03,...,0.03,0.03,0.02,0.03,0.05,0.03,0.03,0.03,0.03,0.01
CRIMINAL DAMAGE,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,...,0.04,0.04,0.03,0.03,0.04,0.04,0.03,0.03,0.03,0.02
CRIMINAL TRESPASS,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.04,0.04,0.03,...,0.03,0.04,0.04,0.03,0.03,0.04,0.04,0.03,0.03,0.02
DECEPTIVE PRACTICE,0.04,0.04,0.03,0.03,0.03,0.04,0.03,0.03,0.03,0.03,...,0.03,0.03,0.03,0.03,0.03,0.04,0.03,0.03,0.03,0.03
GAMBLING,0.07,0.03,0.02,0.01,0.03,0.02,0.03,0.03,0.05,0.04,...,0.02,0.02,0.01,0.04,0.03,0.01,0.02,0.03,0.03,0.03
HOMICIDE,0.02,0.00,0.03,0.02,0.06,0.03,0.02,0.08,0.05,0.05,...,0.02,0.03,0.03,0.03,0.03,0.03,0.02,0.02,0.03,0.02
HUMAN TRAFFICKING,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.50,0.00,0.00,0.00,0.00
INTERFERENCE WITH PUBLIC OFFICER,0.03,0.02,0.05,0.03,0.02,0.04,0.04,0.05,0.04,0.05,...,0.04,0.03,0.02,0.03,0.04,0.03,0.04,0.03,0.03,0.01
INTIMIDATION,0.02,0.04,0.00,0.04,0.02,0.04,0.02,0.02,0.04,0.06,...,0.00,0.04,0.00,0.07,0.00,0.11,0.04,0.02,0.04,0.02
KIDNAPPING,0.02,0.04,0.02,0.04,0.09,0.02,0.00,0.02,0.00,0.02,...,0.00,0.09,0.02,0.06,0.04,0.09,0.02,0.00,0.04,0.00
LIQUOR LAW VIOLATION,0.02,0.05,0.05,0.02,0.02,0.01,0.04,0.01,0.07,0.04,...,0.00,0.01,0.00,0.06,0.00,0.05,0.06,0.02,0.01,0.00
MOTOR VEHICLE THEFT,0.03,0.03,0.04,0.03,0.02,0.04,0.03,0.03,0.03,0.03,...,0.03,0.03,0.04,0.03,0.03,0.03,0.03,0.03,0.04,0.02
NARCOTICS,0.04,0.03,0.04,0.03,0.03,0.04,0.03,0.03,0.03,0.03,...,0.04,0.03,0.03,0.04,0.03,0.03,0.03,0.03,0.03,0.03
NON-CRIMINAL,0.00,0.00,0.00,0.00,0.00,0.12,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.25,0.00,0.00,0.12,0.00,0.12
NON-CRIMINAL (SUBJECT SPECIFIED),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.50,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
OBSCENITY,0.14,0.00,0.05,0.10,0.00,0.05,0.00,0.00,0.00,0.00,...,0.05,0.00,0.05,0.05,0.10,0.10,0.05,0.05,0.05,0.05
OFFENSE INVOLVING CHILDREN,0.06,0.03,0.04,0.04,0.03,0.02,0.03,0.04,0.03,0.04,...,0.03,0.02,0.02,0.03,0.02,0.04,0.03,0.02,0.04,0.02
OTHER OFFENSE,0.04,0.03,0.03,0.03,0.03,0.04,0.04,0.03,0.03,0.03,...,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.02
PROSTITUTION,0.06,0.01,0.02,0.01,0.02,0.02,0.00,0.08,0.01,0.03,...,0.03,0.06,0.03,0.03,0.04,0.05,0.03,0.05,0.09,0.01
PUBLIC INDECENCY,0.00,0.00,0.00,0.20,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
PUBLIC PEACE VIOLATION,0.03,0.04,0.03,0.05,0.03,0.05,0.03,0.04,0.05,0.03,...,0.01,0.03,0.05,0.02,0.04,0.03,0.04,0.02,0.03,0.01
ROBBERY,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.04,0.04,...,0.04,0.03,0.03,0.03,0.04,0.04,0.03,0.04,0.04,0.02
SEX OFFENSE,0.03,0.04,0.01,0.04,0.03,0.03,0.04,0.03,0.03,0.04,...,0.04,0.03,0.03,0.04,0.01,0.01,0.05,0.03,0.03,0.02
STALKING,0.06,0.07,0.06,0.06,0.00,0.06,0.00,0.04,0.04,0.00,...,0.00,0.09,0.06,0.02,0.07,0.00,0.04,0.04,0.02,0.00
THEFT,0.03,0.04,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.04,...,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.02
WEAPONS VIOLATION,0.03,0.03,0.03,0.04,0.04,0.03,0.03,0.03,0.03,0.03,...,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.04,0.03,0.02